### ISSUE TITLE
performance about large board？

### ISSUE THREAD

**Issue by LoranceChen** [jeffkreeftmeijer/hayago#1]
Hi, the snippet code render board and stones. Could be cause performance problem(such as 19x19 board) or futuremore, consider a 100 x 100 board? how about compare with raw `js` implement (if there are) in terms of performance?

```
<div class="board <%= @state.current %>">
  <%= for {value, index} <- Enum.with_index(@state.positions) do %>
    <%= if Hayago.Game.legal?(@game, index) do %>
      <button phx-click="place" phx-value="<%= index %>" class="<%= value %>"></button>
    <% else %>
      <button class="<%= value %>" disabled="disabled"></button>
    <% end %>
  <% end %>
</div>
```

 What I know is the board is render on server side with `for` loop.  
Maybe some strange if all points(on board) be recalculated which cause more cpu usage compare with raw js implement on client.

**Comment by jeffkreeftmeijer** [comment]
Hey @LoranceChen, 

You’re absolutely right, there are a couple of performance issues in the board that aren’t addressed. The whole thing is implemented in a quite naive way to have the code be as illustrative as possible. I might eventually circle back to this to write another article explaining how to make it more performant, but that’s currently not a goal of this example.

Comparing this with raw javascript, the server-side implementation will lose. Implementing the whole thing on the client side will certainly always be faster, if that’s your goal. This was mostly to show off LiveView.
