### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by gcentauri** [jeffkreeftmeijer/hayago#2]
Hi! Thanks for your article and example code. I'm working on a version of it using the https://github.com/unabridged/motion gem for Ruby. I have borrowed the svg and css for your go board and just wanted to make sure that was ok? I may end up replacing them anyway, but just wanted to make sure everything was cool, and I didn't see a license on this repository. I am linking to your article in the docs, please let me know if there's anything else you'd prefer.

**Comment by jeffkreeftmeijer** [comment]
Hey @gcentauri, 

That’s great! Using the assets is fine with me, and it’s great that you’re linking back. I’d love to see the result! Oh, and I’ve added a license to this repository. Thanks for brining this up!

**Comment by gcentauri** [comment]
Hi @jeffkreeftmeijer - Thanks for adding the license :) i can move ahead with a clear conscience. I'll definitely let you know when i get the demo/article finished. Its in a working state (thanks to your example) but I'd like to improve the underlying code to make it simpler to extend. Thanks again!
